### ISSUE TITLE
Empty graphs PRTG

### ISSUE THREAD

**Issue by PirapP** [IzakMarais/reporter#101]
Hi.

I'm trying to create pdf reports from PRTG datasources. I see that everything is find, but the graphs are empty and with a red triangle in top left corner. Can you help to troubleshoot to see what is happening?

Thank you.

**Comment by IzakMarais** [comment]
Are these special PRTG panels? Can you test this using the "Share -> Direct Link rendered image" oprion via the Grafana UI on the panels in question? If the images there give the same problem, then it is a bug in the PRTG panel.

If it is a generic grafana panel, then the problem is likely with the data source setting.  Have a look at this post : https://github.com/IzakMarais/reporter/issues/89#issuecomment-427330669 from someone who also struggled with something similar and fixed it via their data source settings.

**Comment by PirapP** [comment]
I will check it and let you know. Thank you.

**Comment by PirapP** [comment]
Hi.

Is a generic graph Panel.

I teste the direct link share, and Works fine.

I saw that the problem was when the render api was used. It is when the graphs shows empty.

In the logs of Grafana or Reporter there aren't any errors.

I check the post, and I guess then that the problem maybe is on the networks, because the Grafana, and the Datasources are on different networks. I will see if I can make some test on the same Network I see what happen.

Thank you very much.

Have a happy holidays.

**Comment by IzakMarais** [comment]
Thanks for confirming. The best thing to do would be to log a bug with the panel authors.
