### ISSUE TITLE
If a dashboard has few pages in a table, but it only prints the first page.

### ISSUE THREAD

**Issue by jackeylhm** [IzakMarais/reporter#116]
If a dashboard has few pages in a table, but it only prints the first page. I change the "Rows per page" of the data table to a big value and managed to get all data shown in the dashboard. However, when the grafana-reporter download it to pdf, it only shows limited length of the dashboard. Is there any way to adjust the length/width of the converted pdf ? The result is the same even when I ticked off the paging scrolling.

**Comment by IzakMarais** [comment]
Unfortunately I do not think this is possible via the grafana share direct link feature to request multiple table pages (This duplicates #111.)   Perhaps if #72 were fixed so that the reporter would request the table at a larger size depending on the table size in the dashboard, that might work. 

Going to close this for now. Perhaps #72 might address it so you could watch that issue for updates.
