### ISSUE TITLE
Can you provide more help in Command line mode

### ISSUE THREAD

**Issue by PrashantDubeyJi** [IzakMarais/reporter#137]
I am using Command line mode can you provide a help file which shows all the parameters that we can use in command line mode.
One thing more if we are creating a pdf file with screen shots. Can we open those screen shots individually. Can we modify the structure or title of the report like it's showing UTC time zone I want to remove that.

This would be very helpful.

**Comment by IzakMarais** [comment]
All the commandline mode parameters that exist are documented when you call the binary with `--help`. If any spefic one is unclear there, please let me know. 

> One thing more if we are creating a pdf file with screen shots. 

This is not possible, unless you use static images which will be the same for every report.  All dynamic images are rendered by grafana. 

> Can we modify the structure or title of the report 

You can use a custom LaTeX template to modify the structure of the report..
https://github.com/IzakMarais/reporter/issues/50
https://github.com/IzakMarais/reporter/issues/132
https://github.com/IzakMarais/reporter/issues/141

> like it's showing UTC time zone I want to remove that.

  Regarding the timzone, this is not easily cusomisable. If your server timezone is not UTC then the report should respect that (https://github.com/IzakMarais/reporter/issues/43). Otherwise you could use a cusom template and omit the time section all together.
