### ISSUE TITLE
Feature: Grid Layout

### ISSUE THREAD

**Issue by dwitzig** [IzakMarais/reporter#162]
I have added a feature to display panels proportional to the grafana grid layout (see images bellow)

to enable add the `-grid-layout` flag 
basically it uses the grafana gidPos width & height to determine the size when requesting panels.

my commit is here https://github.com/dwitzig/reporter/commit/386bf45eed53145788b095025c5fbcfaa9c4810c 

This may be helpful to others or the owner may want to incorporate.

pls exclude any noob mistakes... my first time with GO :)

<img width="1230" alt="Screen Shot 2019-10-10 at 6 42 01 pm" src="https://user-images.githubusercontent.com/1388617/66553057-27fca000-eb96-11e9-96bc-1ac4fa118d0e.png">
<img width="633" alt="Screen Shot 2019-10-10 at 6 41 48 pm" src="https://user-images.githubusercontent.com/1388617/66553071-2df28100-eb96-11e9-9c32-ac01f7d2e934.png">

**Comment by IzakMarais** [comment]
Wow, this looks very nice, thanks. I would definitely like to include it. 

Would you consider doing a PR? 

Since this code is adding some complexity, it would be good to add test coverage for it. Could you extend the test unit suite? I am thinking maybe:
1.  [here](https://github.com/IzakMarais/reporter/blob/master/grafana/api_test.go#L60) to test that the sizes of the image requests correspond to the panel heights
2. [here](https://github.com/IzakMarais/reporter/blob/master/grafana/dashboard_test.go#L79) to test the JSON parsing of the panel sizes. 

Finally please format your code using `go fmt` (if you use VSCode with the golang plugin and format on save that should happen by default).

**Comment by dwitzig** [comment]
@IzakMarais No problem I'm happy to do a PR

When I'm back in the office I will update the unit tests to cover the changes. Thanks for pointing out where to update. 

I am using VSCode. However not sure if `format on save` is enabled. I will double check this before creating PR

**Comment by IzakMarais** [comment]
Great, thanks!

There are also two open bugs that, if we are lucky, your PR might help to address. They both relate to the hard coded panel sizes. Since you now have dynamic panel sizes based on the dashboard layout, I'm hoping it might solve them.

Would you be willing to try to create a dashboard with some test panels that exercise these cases? Then we can see if your PR fixes them. 🤞 

The first one is https://github.com/IzakMarais/reporter/issues/119, where the panel captions are cut off if there are many traces on the graph. 
The second is https://github.com/IzakMarais/reporter/issues/80, where the text panel height can vary greatly based on the amount of content in it, but the hard coded size can cut off some text that was visible on the dashboard.

**Comment by dwitzig** [comment]
Hi @IzakMarais I have created a new PR with basic test cases for GridLayout and formatted code. Let me know if u find any issues.

One thing to note is X & Y positions are not implemented (I'm not sure if TeX templates support this). So if panel heights are not uniform across each row the PDF render will not match the the Dashboard layout. 

for both #119 & #80 as long as the panel hight on the dashboard is big enough to accommodate the content without scroll bars it will display fine (see bellow). Hopefully that is suitable for others.

<img width="1650" alt="image" src="https://user-images.githubusercontent.com/1388617/66890897-574a5b80-f033-11e9-9877-e003f9daa47d.png">


<img width="1672" alt="image" src="https://user-images.githubusercontent.com/1388617/66890862-3f72d780-f033-11e9-8ef0-21fcaf015fd4.png">

**Comment by IzakMarais** [comment]
Excellent, thanks! 

I'll have a look at the PR now.

**Comment by IzakMarais** [comment]
The commit has been merged. Thanks again for the valuable contribution.
