### ISSUE TITLE
Set file extension for downloaded files

### ISSUE THREAD

**Issue by dmitry84** [IzakMarais/reporter#62]
Currently, when you download a file it doesn't have an extension, just a name which is equal to the dashboard name. This is confusing for some users.

Is it possible to automatically add an extension to the file?

**Comment by dmitry84** [comment]
Thank you very much!

**Comment by IzakMarais** [comment]
Pleasure. I used the dashboard title as the file name, since the dashboard ID can be meaningless in Grafana 5. 

I hope this doesn't introduce bugs, since the dashboard title might have characters in it that are not valid in HTTP headers or in file names. I've tried to sanitise it, so hopefully there should be no strange corner cases.
