### ISSUE TITLE
No external images

### ISSUE THREAD

**Issue by 4rCh3r** [IzakMarais/reporter#63]
The external images in my dashboard appears in blank in the report, is possible fix it or isn't possible add external resources?

**Comment by IzakMarais** [comment]
I have never used external images in a Grafana dashboard. Can you give an example how these are used or point me to the relevant Grafana documentation?

**Comment by 4rCh3r** [comment]
[9kn6uU4ik.pdf](https://github.com/IzakMarais/reporter/files/2080662/9kn6uU4ik.pdf)
<img width="1982" alt="captura de pantalla 2018-06-07 a la s 08 25 54" src="https://user-images.githubusercontent.com/2534565/41103755-84d58f2e-6a2f-11e8-8e62-7a81961c4b60.png">
![untitled 3](https://user-images.githubusercontent.com/2534565/41103756-84ea90f4-6a2f-11e8-86d3-9d60a799295c.png)
![untitled 2](https://user-images.githubusercontent.com/2534565/41103757-85017120-6a2f-11e8-9618-c369cc7b4f6f.png)

I tried using html and the plugin "PictureIt" but the result is the same.

**Comment by IzakMarais** [comment]
Ok this appears to be a bug in the Grafana share functionality, which is used by the reporter to render the images. To verify this, go to your text panel with the image, click on the title -> _Share_ -> _Direct link rendered image_. Notice that here the image is also not rendered. Since this is the url used by the reporter, it explains why images are missing from text panels in you report.

**Comment by IzakMarais** [comment]
I logged an issue on the Grafana project: https://github.com/grafana/grafana/issues/12210

**Comment by 4rCh3r** [comment]
Ok, thanks. Now I'll just wait for the fix.

**Comment by IzakMarais** [comment]
Given that https://github.com/grafana/grafana/issues/12210 has been accepted as a grafana bug and is open, progress can be tracked there. I am going to close this issue.
